spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: authority_route
          uri: lb://mem-authority
          predicates:
            - Path=/api/authority/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: authority_route
          uri: lb://mem-file
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
server:
  port: 9500
logging:
  level:
    root: debug
