spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: authority_route
          uri: lb://mem-authority
          predicates:
            - Path=/api/authority/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: im_route
          uri: lb:ws://mem-im
          predicates:
            - Path=/im/websocket
        - id: im_route
          uri: lb://mem-im
          predicates:
            - Path=/api/im/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: file_route
          uri: lb://mem-file
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: user_route
          uri: lb://mem-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
server:
  port: 9500
logging:
  level:
    root: info
